[package]
name = "voting-system"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["abigen", "ws", "rustls"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
eyre = "0.6"
